### PR TITLE
refactor(vendor-core): remove unused packages from vendor core

### PR DESCRIPTION
**Pull request by MariaAga**
removes 'react-numeric-input','react-markdown', 'isomorphic-fetch'

https://github.com/theforeman/foreman/pull/5080 - removed 'react-markdown'
https://github.com/theforeman/foreman/pull/7725 - added 'isomorphic-fetch' but was never merged
https://github.com/theforeman/foreman/pull/7896 - removed  'react-numeric-input'

### CODE REVIEW

**Review by sharvit — APPROVED** [review]
Thanks @MariaAga LGTM

**Comment by sharvit** [comment]
As described here: https://github.com/theforeman/foreman-js/blob/master/docs/managing-vendor-dependencies.md#remove-a-vendor-dependency

> Removing a package is similar to updating a package, but we will always describe **BREAKING CHANGES** in the commit message, and the CI should release a **Major** version to npm.
I am ok getting it merged as it is because it doesn't actually break anything but might be worth considering anyway just so we keep a clear changelog.

**Comment by MariaAga** [comment]
Thanks! changed the commit message

**Comment by sharvit** [comment]
Need to change the text in the commit from BREAKING CHANGE to BREAKING CHANGE**S**

**Comment by MariaAga** [comment]
https://github.com/theforeman/foreman-js/blob/7fa9adbe848f7c24e8bf67e62977e1d1193afb59/.cz-config.js#L75
Should we change this to `BREAKING CHANGES` as well?

**Comment by sharvit** [comment]
It's odd, I guess the tool will accept both...

You are welcome to change it in another PR, merging...

**Pull request merged**
