### PR TITLE
fix(test): run test when installing from source

### PR DESCRIPTION
**Pull request by sharvit**
This will make sure tests can run when installing
@theforeman/test from source

ISSUES: fixes #GH-119

## Updated Packages

* [ ] root
* [ ] @theforeman/builder
* [x] @theforeman/test
* [ ] @theforeman/eslint-plugin-foreman
* [ ] @theforeman/stories
* [ ] @theforeman/vendor
* [ ] @theforeman/vendor-dev
* [ ] @theforeman/vendor-core

## PR Type

* [x] Bugfix
* [ ] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Other… Please describe:

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

## Does this PR fixes open issues?

* [x] Yes - #GH-119
* [ ] No

## Do you use this PR in another repository?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by sharvit** [comment]
This can be tested by installing locally:
```diff
-    "@theforeman/test": "^4.0.2",
+    "@theforeman/test": "../foreman-js/packages/test",
```

Or by installing from npm:
```diff
-    "@theforeman/test": "^4.0.2",
+    "@theforeman/test": "4.0.6-run-tests-locally.0",
```

**Comment by xprazak2** [comment]
Fixes the missing jest issue for me.

**Comment by sharvit** [comment]
@amirfefer can you have a look please?

**Pull request merged**
