### PR TITLE
feat(test): add @apollo/react-testing

### PR DESCRIPTION
**Pull request by xprazak2**
Adds @apollo/react-testing package which provides
testing utilities for apollo client.

### CODE REVIEW

**Comment by xprazak2** [comment]
Wait, should this be in vendor-core if we only need it for testing?

**Comment by ezr-ondrej** [comment]
> Should this be in vendor-core if we only need it for testing?

I believe not, but unsure here, `vendor-dev` / `test` packages would make more sense to me.

**Comment by tbrisker** [comment]
Probably test package makes sense, as this is only used for testing.

**Comment by xprazak2** [comment]
Moved to test.

**Comment by tbrisker** [comment]
I'm not sure why but it seems the failing tests are failing to find the `jest-transform-graphql` module?
```
Module jest-transform-graphql in the transform option was not found.
         <rootDir> is: /home/runner/work/foreman-js/foreman-js/projects/foreman

**Review by tbrisker — APPROVED** [review]
Thanks @xprazak2 !

**Pull request merged**
