### PR TITLE
feat(vendor-core): update Redux 

### PR DESCRIPTION
**Pull request by amirfefer**
## PR Type

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Other… Please describe:

## Does this PR introduce a breaking change?

- [x]  Yes
* [ ] No

### CODE REVIEW

**Comment by sharvit** [comment]
Thanks @amirfefer :+1:  Looks like there are some conflicts.

**Comment by ezr-ondrej** [comment]
Could we get this one in? :fox_face: :upside_down_face:

**Comment by amirfefer** [comment]
@sharvit - updated with the new commit :)

**Comment by amirfefer** [comment]
rebased

**Pull request merged**
