### PR TITLE
feat(vendor-core): bump all pf4 packages to version 4

### PR DESCRIPTION
**Pull request by MariaAga**
BREAKING CHANGE:
https://www.patternfly.org/v4/documentation/react/overview/upgrade-guide |
https://www.patternfly.org/v4/documentation/core/overview/upgrade-guide

## Updated Packages

* [ ] root
* [ ] @theforeman/builder
* [ ] @theforeman/test
* [ ] @theforeman/eslint-plugin-foreman
* [ ] @theforeman/stories
* [ ] @theforeman/vendor
* [ ] @theforeman/vendor-dev
* [x] @theforeman/vendor-core
* [ ] @theforeman/find-foreman

## PR Type

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Other… Please describe:

## Does this PR introduce a breaking change?

* [x] Yes
* [ ] No

## Does this PR fixes open issues?

* [ ] Yes
* [ ] No

## Do you use this PR in another repository?

* [ ] Yes
* [ ] No

### CODE REVIEW

**Comment by sharvit** [comment]
Thanks @MariaAga, I am wondering if we should release a breaking-changes release or a normal one.
Does it actually break something in foreman or in a plugin? In my tests, look like it doesn't...

**Comment by johnpmitsch** [comment]
@MariaAga @sharvit what is the best way to test this out? I would like to test it out with what is merged for the new content view page so far

**Comment by sharvit** [comment]
> @MariaAga @sharvit what is the best way to test this out? I would like to test it out with what is merged for the new content view page so far

clone the pr and run `npm i && npm run build`, then, run `npm run foreman-js:link` in foreman.
see: https://foreman-storybook.surge.sh/?path=/docs/introduction-adding-dependencies--page

**Comment by MariaAga** [comment]
@sharvit I didn't notice it broke something in foreman core, do we use any PF4 in core?

**Comment by johnpmitsch** [comment]
Thanks for the info, I see breaking changes in Katello on the new CV page, which uses patternfly 4 (but the major version 3 of it- uggh pf versioning). Here is something not seen on the current version:

```
react.development.js:172 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Title`.
    in Title (created by Loading)
    in div (created by EmptyState)
    in div (created by EmptyState)
    in EmptyState (created by Loading)
    in div (created by Bullseye)
    in Bullseye (created by Loading)
    in Loading (created by MainTable)
    in MainTable (created by TableWrapper)
    in TableWrapper (created by ContentViewTable)
    in ContentViewTable (created by ContentViewsPage)
    in ContentViewsPage (created by Context.Consumer)
    in withRouter(ContentViewsPage) (created by Headers)
    in Headers (created by Context.Consumer)
    in Route (created by _default)
    in div (created by _default)
    in _default (created by Application)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Application)
    in Application (created by ConnectFunction)
    in ConnectFunction (created by I18nProviderWrapper(Connect(Application)))
    in IntlProvider (created by I18nProviderWrapper(Connect(Application)))
    in I18nProviderWrapper(Connect(Application)) (created by StoreProvider(I18nProviderWrapper(Connect(Application))))
    in Provider (created by StoreProvider(I18nProviderWrapper(Connect(Application))))
    in StoreProvider(I18nProviderWrapper(Connect(Application))) (created by DataProvider(StoreProvider(I18nProviderWrapper(Connect(Application)))))
    in DataProvider(StoreProvider(I18nProviderWrapper(Connect(Application))))
```

There is also some WIP that would need to be updated. I think a major version bump would be appropriate so things don't break right away, and we can update Katello along with the version bump in Foreman in a coordinated way.

**Comment by johnpmitsch** [comment]
> Can this issue be fixed before we merge this PR or it has to be done together (consume and migrate)?

It will be fine if there is a major version bump of the packages here, and then a PR to update Foreman's package.json can be done with a Katello PR to fix the issue. I think this would make the most sense, it is a breaking change because of the new patternfly major version.

If you want to do a minor version bump, we'll have to fix Katello before this is merged as the changes will be pulled in when updating npm packages or fresh installs.

**Comment by johnpmitsch** [comment]
I looked into it and the changes weren't too bad, I opened up https://github.com/Katello/katello/pull/8795 which I think covers all of them. Feel free to do a minor release if preferred now that a Katello PR is open.

**Comment by jturel** [comment]
Is this code meant to be backported to foreman 2.1?

**Pull request merged**
