### PR TITLE
add react-loading-skeleton package

### PR DESCRIPTION
**Pull request by glekner**
## PR Type

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Other… Please describe:

## Description
Add `react-loading-skeleton` package to core

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by sharvit** [comment]
Thanks @glekner :+1: 

1. Can you please paste the foreman related PR here?
2. Is this important to foreman `1.23`? If not we will need to delay it after foreman branching

**Comment by glekner** [comment]
1. https://github.com/theforeman/foreman/pull/6733
2. I'd say we want to merge the Audits route before merging

**Comment by glekner** [comment]
@sharvit can we merge now?

**Comment by sharvit** [comment]
Yes!

can you rebase, `npm run clean` and `npm install` again please?

**Comment by sharvit** [comment]
And please recommit your changes using: `npm run commit` (new convention)

**Comment by glekner** [comment]
done @sharvit

**Comment by glekner** [comment]
- added to `modules.js`

**Pull request merged**
