### PR TITLE
fix(deps): bump jest

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Seems like jest-svg-transformer is not compatible with jest 27, so plugins that use it would need to find an alternative.

**Comment by ezr-ondrej** [comment]
> jest-svg-transformer

I don't believe we have some :shrug:

**Comment by ezr-ondrej** [comment]
All seems green to me, lets see it in action.

**Comment by xprazak2** [comment]
I believe we do:
https://github.com/theforeman/foreman_leapp/blob/master/package.json#L39
https://github.com/theforeman/foreman_openscap/blob/master/package.json#L42

**Comment by sjha4** [comment]
We are getting some errors on the Katello test suite: 

`● Test suite failed to run

    TypeError: snapshotResolver.resolveSnapshotPath is not a function

      at Object._default [as default] (node_modules/jest-jasmine2/build/setup_jest_globals.js:101:41)`

Seems related to upgrading jest-jasmine2 as part of this.

**Comment by Andrewgdewar** [comment]
I would suggest **reverting** this change, until a change can be made that does not cause plugin test failures.

**Comment by xprazak2** [comment]
I agree, I have already opened a [revert](https://github.com/theforeman/foreman-js/pull/346). I did not get the jasmine error when doing the bump but it shows on the revert PR...

**Pull request merged**
