### PR TITLE
Bump nodejs-patternfly-react to 2.36.6

### PR DESCRIPTION
**Pull request by amirfefer**
## PR Type

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Other… Please describe:

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by sharvit** [comment]
@amirfefer Can you please past the foreman PR here?

You need to run `npm install` so the `package-lock.json` will get updated: https://travis-ci.org/theforeman/foreman-js/builds/557234805#L483-L486

**Comment by xprazak2** [comment]
Foreman PR: https://github.com/theforeman/foreman/pull/6841

**Comment by sharvit** [comment]
Is this foreman `1.23` feature?

**Comment by xprazak2** [comment]
No target release is set, so I do not think this is critical.

We do not need to have it in 1.23 if it would mean delaying branching or causing complications for packaging.

**Comment by glekner** [comment]
update? https://github.com/theforeman/foreman/pull/6841 is blocked by this

**Comment by sharvit** [comment]
@amirfefer can you rebase, reinstall and recommit using `npm run commit`?

**Comment by ezr-ondrej** [comment]
Thanks @amirfefer, but closing this as in the `master` we have patternfly 2.36.8 already.

**Pull request closed without merging**
