### PR TITLE
fix(vendor-core): pin frontend-component-utilities

### PR DESCRIPTION
**Pull request by sjha4**
pin frontend-component-utilities

### CODE REVIEW

**Comment by MariaAga** [comment]
Added a pr to run tests on node 14, did you run npm i? I would assume there would also be package-lock changes

**Comment by sjha4** [comment]
Not sure if it's a problem but is there a suggested npm version to run npm i here? I see the package-lock got completely rewritten with "lockfileVersion": 2 on npm 8.19.2 I have locally.

```
npm i
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
```

**Comment by sjha4** [comment]
Thanks @MariaAga .. Updated with package-lock from npm 6..

**Comment by MariaAga** [comment]
Tests didnt get to use foreman-js as they fail in npm i.
Thanks Samir!

**Pull request merged**
