### PR TITLE
feat(vendor-core): add D&D react library

### PR DESCRIPTION
**Pull request by ezr-ondrej**
## Updated Packages

* [ ] root
* [ ] @theforeman/vendor
* [ ] @theforeman/vendor-dev
* [x] @theforeman/vendor-core

## PR Type

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Other… Please describe:

## Description

Adding a package implementing drag & drop support.

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by sharvit** [comment]
Thanks @ezr-ondrej :+1: 

1. You will need to add your modules to https://github.com/theforeman/foreman-js/blob/master/packages/vendor-core/lib/modules.js so they will be available.

2. Since this PR bring new features, please edit your commit to: `feat(vendor-core): ...`, notice this project use `npm run commit` to automate commit creations.
(Later we will calculate version changes based on those commit messages)

3. I would recommend you to use `npm run foreman-js:link` so you can test it locally with foreman and plugins: https://github.com/theforeman/foreman/blob/develop/package.json#L9

**Comment by ezr-ondrej** [comment]
Thanks @sharvit for the notes, finally got to the addressing.
Added the modules, tested locally and everything works.

**Comment by ezr-ondrej** [comment]
Rebased :man_shrugging:

**Comment by ezr-ondrej** [comment]
@sharvit ? Is this missing something?

**Pull request merged**
