### PR TITLE
feat(vendor-core): update @patternfly/react-core to 4.128.6

### PR DESCRIPTION
**Pull request by xprazak2**
Updates @patternfly/react-core package to version 4.128.6

### CODE REVIEW

**Comment by MariaAga** [comment]
Thanks for the update, can you update the rest of the pf packages so they all be from the same release? https://www.patternfly.org/v4/developer-resources/release-notes#2021.07-release-notes-2021-06-04

**Comment by xprazak2** [comment]
Updated, snapshots in rh_cloud will need an update afterwards.

**Comment by MariaAga** [comment]
Thanks @xprazak2 !

**Comment by tbrisker** [comment]
Looks like core snapshots also need update: https://github.com/theforeman/foreman/runs/2940667891?check_suite_focus=true

**Pull request merged**
