### PR TITLE
Adds @patternfly/react-table

### PR DESCRIPTION
**Pull request by johnpmitsch**
## Updated Packages

* [ ] root
* [ ] @theforeman/builder
* [ ] @theforeman/test
* [ ] @theforeman/eslint-plugin-foreman
* [ ] @theforeman/stories
* [ ] @theforeman/vendor
* [ ] @theforeman/vendor-dev
* [x] @theforeman/vendor-core

## PR Type

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Other… Please describe:

## Description

This adds `@patternfly/react-table`, which is part of the patternfly 4 react packages

## Does this PR introduce a breaking change?
no

* [ ] Yes
* [x] No

## Does this PR fixes open issues?

* [ ] Yes
* [x] No

## Do you use this PR in another repository?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by waldenraines** [comment]
> Do you use this PR in another repository?

Won't we though?

**Comment by johnpmitsch** [comment]
> > Do you use this PR in another repository?
> 
> Won't we though?

I didn't really understand this question, I would assume anything added to this repo would be used in another repository, I thought it was asking about an accompanying PR. Maybe @sharvit can clear up what this means.

**Comment by johnpmitsch** [comment]
@sharvit @amirfefer Some feedback for this repo: It would be nice to have some more docs and examples for the commit linter, I spent some time fighting with it and had to dig through it's documentation. I didn't see any guidelines in the contributing docs here

**Comment by johnpmitsch** [comment]
Everything is passing now :+1:

**Comment by sharvit** [comment]
> > > Do you use this PR in another repository?
> > 
> > 
> > Won't we though?
> 
> I didn't really understand this question, I would assume anything added to this repo would be used in another repository, I thought it was asking about an accompanying PR. Maybe @sharvit can clear up what this means.

Yes, usually I prefer to see a WIP PR to core/plugin just to prof the concept before merging.
In this case, it's redundant.

**Comment by sharvit** [comment]
> @sharvit @amirfefer Some feedback for this repo: It would be nice to have some more docs and examples for the commit linter, I spent some time fighting with it and had to dig through it's documentation. I didn't see any guidelines in the contributing docs here

The point is that you shouldn't write the commit message yourself and use the `npm run commit` instead.
https://github.com/theforeman/foreman-js/blob/master/CONTRIBUTING.md#creating-pull-requests

What would you suggest instead? a pull request would be nice :)

Thanks!

**Comment by johnpmitsch** [comment]
> The point is that you shouldn't write the commit message yourself and use the `npm run commit` instead.
> https://github.com/theforeman/foreman-js/blob/master/CONTRIBUTING.md#creating-pull-requests

@sharvit  ah ok, that makes more sense now, I read that as the linter command but re-reading it it makes a lot more sense now :) No wonder I had trouble. Thanks for explaining and sorry for the noise!

**Pull request merged**
