### PR TITLE
Test Commit to see failures

### PR DESCRIPTION
**Pull request by sjha4**
Text update to check if CI is using old node_modules.

### CODE REVIEW

**Comment by sjha4** [comment]
@Andrewgdewar : Seems your theory is correct. The CI tests are run against the old modules and are broken on those. 

@xprazak2 Could be we are missing a npm build step in the CI before the link? Atleast that's what the documentation says and I don't see that happening in the workflow..

**Comment by ezr-ondrej** [comment]
> missing a npm build step in the CI before the link?

I don't think we need a build step, this seems like a real error, I've seen this locally while trying somthing with `foreman-js` this week. I failed to resolve it and thought it was just my issue tho :shrug: xD

**Comment by sjha4** [comment]
@ezr-ondrej - This happens only on 8.12.1 that has a single change of upgrading jest. The fix should be this: https://github.com/theforeman/foreman-js/pull/346 but that is failing with the same errors. We should have seen these errors on the original PR to upgrade jest, leading us to believe the tests aren't being run against the packages in the PR but the last release of foreman-js for some reason.

**Comment by xprazak2** [comment]
I observed that `npm install` with `@theforeman-package@x.y.z` in package.json is not the same as `npm install` with `@theforeman-package@x.y.z-1` and linking the x.y.z version afterwards. When we link the newer version of the package, `node_modules` still contain packages that were resolved and installed for the older version. So packages for jest 27 are still being pulled when testing the revert PR.

We should probably think about how to point to the new version before `npm install` in the future.

I see 2 possible approaches to move forward in fixing the tests:
A)
* merge the revert for jest in foreman-js with failing katello tests. Once new version of @theforeman is released, it will be pulled in and tests should be green

B)
* pin @theforeman to 8.12.0 in foreman repo which should make katello tests green
* merge jest revert
* unpin @theforeman

**Comment by sjha4** [comment]
Closing this.. The foreman PR to pin foreman-js to <8.12.1 is merged. We should look to merge the foreman-js jest revert PR too and see if tests go green..

**Pull request closed without merging**
