### PR TITLE
feat(vendor-core): adds @patternfly/react-styles

### PR DESCRIPTION
**Pull request by MariaAga**
Adds @patternfly/react-styles, the version is from the[ 2020.08 PF release ](https://www.patternfly.org/2020.08/documentation/react/overview/release-notes)
## Updated Packages

* [ ] root
* [ ] @theforeman/builder
* [ ] @theforeman/test
* [ ] @theforeman/eslint-plugin-foreman
* [ ] @theforeman/stories
* [ ] @theforeman/vendor
* [ ] @theforeman/vendor-dev
* [x] @theforeman/vendor-core
* [ ] @theforeman/find-foreman

## PR Type

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Other… Please describe:

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

### CODE REVIEW

**Comment by MariaAga** [comment]
Added to modules, the css in there is for PF example files, thanks!

**Comment by sharvit** [comment]
Thanks! can you please rebase? we were just merged the github-actions PR so it will get tested against foreman/-tasks/katello.

**Comment by MariaAga** [comment]
Looks like there is an issue in the `Run foreman-js commit linter` test

**Comment by sharvit** [comment]
> Looks like there is an issue in the `Run foreman-js commit linter` test

Yes, @laviro fixed that already, I wouldn’t rebase because the commit-lint ran in travis anyway

**Pull request merged**
