### PR TITLE
fix(test): fix tests to work similar using npm or local

### PR DESCRIPTION
**Pull request by sharvit**
## Updated Packages

* [ ] root
* [ ] @theforeman/builder
* [x] @theforeman/test
* [ ] @theforeman/eslint-plugin-foreman
* [ ] @theforeman/stories
* [ ] @theforeman/vendor
* [ ] @theforeman/vendor-dev
* [ ] @theforeman/vendor-core
* [ ] @theforeman/find-foreman

## PR Type

* [x] Bugfix
* [ ] Feature
* [ ] Code style update (whitespace, formatting, missing semicolons, etc.)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Other… Please describe:

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

## Does this PR fixes open issues?

* [ ] Yes
* [x] No

## Do you use this PR in another repository?

* [x] Yes - https://github.com/theforeman/foreman/pull/7788
* [ ] No

### CODE REVIEW

**Comment by johnpmitsch** [comment]
I haven't followed all the developments around this area, what are the actual issues we are seeing here? 

In Katello, we use find-foreman to load the relative foreman directories containing `node_modules` https://github.com/Katello/katello/blob/master/jest.config.js#L31-L32 - I was hoping to introduce something like this here as it would work for both Foreman and plugins, but not sure if I'm missing some larger issues.

**Comment by sharvit** [comment]
> I haven't followed all the developments around this area, what are the actual issues we are seeing here?

The issue is that jest might resolve the wrong node_module when you end up with 2 different versions of the same module.
I don't think the "katello approach" would help in this case.

**Comment by johnpmitsch** [comment]
> The issue is that jest might resolve the wrong node_module when you end up with 2 different versions of the same module.
> I don't think the "katello approach" would help in this case.

@sharvit are we seeing this for plugins or for Foreman core?

**Comment by sharvit** [comment]
> @sharvit are we seeing this for plugins or for Foreman core?

foreman core :(

**Comment by sharvit** [comment]
I think this is the best we can do for now as there are differences between nodejs v10 to v12.

If you are using v12, both `npm i && npm test` and `npm run foreman-js:link && npm test` should work.
If you are using v10, only `npm i && npm test` while`npm run foreman-js:link && npm test` **would not** work.

**Comment by johnpmitsch** [comment]
@sharvit gotcha, thanks for explaining!

**Comment by sharvit** [comment]
> I haven't tested anything out, but the code looks fine
> 
> Just a general question, is there a reason to test on more than one nodejs version?

Well, I am not sure how to answer that, from one side we can decide we only support development using nodejs-12 and it will be easier to deliver more consistency, from the other side, today we support v12 and v10 (we test both of them in Travis) and I want to keep the current setup working.

**Comment by johnpmitsch** [comment]
> Well, I am not sure how to answer that, from one side we can decide we only support development using nodejs-12 and it will be easier to deliver more consistency, from the other side, today we support v12 and v10 (we test both of them in Travis) and I want to keep the current setup working.

@sharvit If our build/release environment uses nodejs12 (I think it does) and the dev environment uses nodejs12 (Katello does, but not sure about foreman's), can we drop nodejs 10 testing?

**Comment by sharvit** [comment]
> > Well, I am not sure how to answer that, from one side we can decide we only support development using nodejs-12 and it will be easier to deliver more consistency, from the other side, today we support v12 and v10 (we test both of them in Travis) and I want to keep the current setup working.
> 
> @sharvit If our build/release environment uses nodejs12 (I think it does) and the dev environment uses nodejs12 (Katello does, but not sure about foreman's), can we drop nodejs 10 testing?

IMO yes

**Pull request merged**
