### PR TITLE
feat(root): drop stories package

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by MariaAga** [comment]
@adamruzicka Can you add in the commit that its a breaking change with `npm run commit`?

**Comment by MariaAga** [comment]
@adamruzicka is this still in progress ?

**Comment by adamruzicka** [comment]
Nope, I originally opened it as a draft in case I was doing something silly and then forgot about it

**Comment by MariaAga** [comment]
Thanks! Didnt see any more plugins using it so hopefully nothing breaks

**Pull request merged**
